#!/usr/bin/ruby
 
def change_log(stream)
  ActiveRecord::Base.logger = Logger.new(stream)
  ActiveRecord::Base.clear_active_connections!
end
      
def show_log
  change_log(STDOUT)
  reload!
end

def hide_log
  change_log(nil)
  reload!
end

def show_session(cookie)
  Marshal.load(Base64.decode64(CGI.unescape(cookie.split("\n").join).split('--').first))
end
